### ISSUE TITLE
Missing / Wrong sequencer identifiers in templates

### ISSUE THREAD

**Issue by mobilegenome** [usegalaxy-eu/ena-upload-cli#11]
Hi, 

when I processed some of our data, the data validation failed with an error message relating to missing "Illumina" elements in the XML. I could solve this by adding the following lines to

ENA_template_PLATFORM.XML (l.28):
```<INSTRUMENT_MODEL py:when="row.instrument_model.lower().strip() == 'illumina novaseq 6000'">Illumina NovaSeq 6000</INSTRUMENT_MODEL>```

SRA.common.xsd (l.911):
```<xs:enumeration value="Illumina NovaSeq 6000"/>```

In course of doing this, I also noticed that the *NextSeq*  and *HiSeq X* platforms are listed without the Illumina prefix, e.g. 

```
<INSTRUMENT_MODEL py:when="row.instrument_model.lower().strip() == 'illumina hiseq 4000'">Illumina HiSeq 4000</INSTRUMENT_MODEL>
<INSTRUMENT_MODEL py:when="row.instrument_model.lower().strip() == 'nextseq 550'">NextSeq 550</INSTRUMENT_MODEL>
```

I'm happy to provide a PR for this, however, I wonder if this is the clean way to do or if the files were originally fetched from ENA and should be rather fixed there. 

Best

Fritjof

**Comment by bedroesb** [comment]
@mobilegenome thank you for spotting this! It seems that our templates are outdated. I will open a PR updating the cli tool with the latest .xsd files of ENA and ping you.
