### ISSUE TITLE
Changing release date through API

### ISSUE THREAD

**Issue by bedroesb** [usegalaxy-eu/ena-upload-cli#36]
Now it is only possible to change the release data manually though the website.

**Comment by roncoronimiguel** [comment]
Release can be set as an ACTION in the Submission XML to HOLD, RELEASE (immediately) or HOLD (until date). Could we have a '--release' flag to mirror these options and behaivour

**Comment by bedroesb** [comment]
Why not using the existing action parameter for this?

**Comment by roncoronimiguel** [comment]
yes, whichever way works. It would be nice to have the option of immediate release
