### ISSUE TITLE
Possibility to give the taxon_id through the table 

### ISSUE THREAD

**Issue by bedroesb** [usegalaxy-eu/ena-upload-cli#6]

**Comment by rabuono** [comment]
Suggestion:
Currently the tool fetches a `taxon_id` based on the the provided `scientific_name`.
It would be nice if it was the inverse. If a value in `taxon_id` would be used to fetch the most appropriate value for the `scientific_name`.
Users could be directed to [NCBI's Taxonomy Browser](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi) or to [EBI's OLS page for NCBItaxon page](https://www.ebi.ac.uk/ols/ontologies/ncbitaxon) to search for the appropriate value to enter for `taxon_id`.

In this scenario, a User input value for `scientific_name` would be overwritten by a value based on `taxon_id`. Also, a valid `taxon_id` value would be mandatory.
