### ISSUE TITLE
Correct criteria for a successful submission

### ISSUE THREAD

**Issue by wna-se** [usegalaxy-eu/ena-upload-cli#66]
I don’t think that the success attribute of the XML receipt can be [used as an indicator of a successful submission](https://github.com/usegalaxy-eu/ena-upload-cli/blob/0cb023da28f6b561fdb725a656ae98fc78c76fb0/ena_upload/ena_upload.py#L481). You would still need to parse the content to look for errors and successfully allocated accession numbers in the body of the receipt, see for example from the [corresponding implementation in the webin-cli by ENA](https://github.com/enasequence/webin-cli/blob/f3ab8a9a8ea351e39df5459f8711791f0fe7a682/src/main/java/uk/ac/ebi/ena/webin/cli/service/SubmitService.java#L138)

**Comment by bedroesb** [comment]
I am not sure if I am following since the accession numbers are parsed from the receipt + dumped into the updated tables and printed out in the stdout

**Comment by wna-se** [comment]
Sorry about that. I've spend too much time in meetings and my mailbox today and totally misread function.
