### ISSUE TITLE
Submitting new project to ENA

### ISSUE THREAD

**Issue by Najatamk** [usegalaxy-eu/ena-upload-cli#95]
Hello,
I'm attempting to submit non-viral raw reads to ENA using the test Webin submission portal. The tool appears to be functioning correctly, but it isn't creating a new project on the ENA portal. The files only become accessible the next day under the "Unsubmitted files" section. Is this normal? How can I successfully submit a project?
Let me know if you need more informations.
Thank you .

**Comment by bedroesb** [comment]
Hello @Najatamk, thanks for reaching out. You tried out a submission using this command line tool with data and a spreadsheet with the metadata? I will do a test submission myself to see if I encounter problems.

**Comment by Najatamk** [comment]
Hello! 
Thank you for responding and looking into it.
I used the Galaxy tool with data and for the metadata input method i used the option 'interactively'.
I also tried with a spreadsheet option but got similar results.

**Comment by bedroesb** [comment]
I just did it with the ENA upload CLI which should be the same as the one in Galaxy, and after a successful submission I could login into https://wwwdev.ebi.ac.uk/ena/ and go to the run Files report section where the uploaded files are immediately available: https://wwwdev.ebi.ac.uk/ena/submit/webin/report/runFiles;defaultSearch=true. Which Galaxy instance are you using?

**Comment by Najatamk** [comment]
Hello , I just tried again and it worked this time.
Thank you again for your help.

**Comment by bedroesb** [comment]
That's great to hear! I can close this issue than I think :)
