### ISSUE TITLE
Submitting paired reads plus their indices

### ISSUE THREAD

**Issue by mobilegenome** [usegalaxy-eu/ena-upload-cli#96]
Hi, 

we're currently preparing a submission for the (now discontinued) linked-read sequencing from 10X Genomics. Similar to the current 10X single-cell RNA-Seq datasets, our datasets consists of two paired-end FASTQ files plus an index file. The data is whole-genome sequencing, so I suppose ENA is the correct place to submit them. 

However, for each set of RUNs that includes an index file, ena-upload-cli returns the following error. Is this something I can mitigate on my end, or is it tool or even an issue for ENA?

Error:
```
Oops:
In run, alias: "<...>". Read type information missing in run.
````

Thanks and best, 
Fritjof

**Comment by bedroesb** [comment]
Hello @mobilegenome. I personally do not have experience with submitting the index file. Could you give me an example of a row in your run sheet? It can be anonymized off course. The error itself is returned by ENA and is not one thrown by the tool.

**Comment by mobilegenome** [comment]
Hi @bedroesb, 

it seems that indeed ENA simply does not allow for readsets were each RUN consists for three files. We have now come around it by submitting via NCBI... 

Thanks anyway and best wishes.
